/**x
 * Custom javascript calls for TBN
 * -------------------------------
 */

jQuery(document).ready(function($) {
	

	// jQuery - adding classes for bootstrap styling. In the most cases the elements
	// where the classes are added are autogenerated from wordpress.
	// -----------------------------------------------------------------------------
	$('.widget_calendar table').addClass('table');
});